UNLV-CS472-672/2024-S-GROUP8-CW

Crypto Wars/Assets/Scripts/PlayerScript.cs
- Will be referencing things in future, especially from tiles and turnMaster
- Still needs thing like a tile reference system and inventory
=> Added constructor, and basic data gathering for player focused values

Crypto Wars/Assets/Scripts/CameraScript.cs, Crypto Wars/Assets/Scripts/CameraScript.cs.meta
Added functionality for WASD user input to control the cameras X and Y axis.
=> Feature added: simple WASD camera controls for Main Camera

Crypto Wars/Assets/Scripts/PlayerScript.cs, Crypto Wars/Assets/Scripts/TurnMaster.cs
I added in the implementation for the TurnMaster class. I did this by adding in two additional methods to check for the status of the player's turns and resetting the player's turns. Whenever all players have finished their turn or after a certain amount of time (currently 30 seconds but can be easily changed)  it increments the currTurn variable and resets the isDone variable in all player objects. I also fixed some of the code in PlayerScripts. There appeared to be a missing semicolon and a couple of methods that should have void as their return type did that.
=> Added in the code for the TurnMaster class

Crypto Wars/Assets/Scripts/PlayerController.cs, Crypto Wars/Assets/Scripts/PlayerController.cs.meta, Crypto Wars/Assets/Scripts/PlayerScript.cs, Crypto Wars/Assets/Scripts/TileScript.cs, Crypto Wars/Assets/project.unity, Crypto Wars/Assets/project.unity.meta
PlayerScript
- Needs comments still
- Detects player clicks
- Manages the players in the game
TileScript
- Refactored code to allow for as many players as we want
- Needs more comments
Implements #12
=> Refactored TileScript and Added PlayerScript

Crypto Wars/Assets/Scripts/Building_Abstract.cs, Crypto Wars/Assets/Scripts/Building_Abstract.cs.meta, Crypto Wars/Assets/Scripts/PlayerScript.cs, Crypto Wars/Assets/Scripts/TurnMaster.cs
Created the following variables along with their getters and setters:
private int amount - the amount of cards the buidling produces 
private int turnsToProduce - how long it takes for this cards to be produced
private int turnsSinceLastProdction - how long since the last time the buidling produced cards
private CardClass producedCard - the card the buidling produces
private PlayerScript owner - the player of that owns the building
private TileScript currentTile - the tile the building is on
Also created the following method:
addCardsToInventory - Checks to see if it is time to make new cards. If it is add the new cards to the inventory and reset the counter for turnsSinceLastProduction to 0
=> Added in the Abstract Class for Building

Crypto Wars/Assets/Scripts/Battles.cs
This PR included the implementation for the Battle class. This class is responsible for determining if the type of battle calculations done based on if the players are attacking adjacent tiles or not as well as actually conducting the battle. If adjacent tiles are not being attacked then the players are prompted to select defense cards from whatever cards are stored in their cards array. As the Cards class is implemented that array will be used. Additionally the specific calculations for the battle will be used here but will most likely be implemented elsewhere. 
Fixes #16
=> Implemented WIP Battle Class Script

Crypto Wars/Assets/Scripts/CardClass_Abstract.cs, Crypto Wars/Assets/Scripts/CardClass_Abstract.cs.meta
In correlation with Issue  #10 
Added an abstract card class for future use. This class contains a struct for storing the stats of the individual card. There are also basic getters/setters for each stat of the card. The class also has a GameObject card, this is for displaying an actual card in Unity. I wrote a method for setting the card's status to active, which activates the object in-game.
=> Add Abstract CardClass

Crypto Wars/Assets/Scripts/PlayerScript.cs, Crypto Wars/Assets/Scripts/TileScript.cs
Adds storage for tiles that the current Player owns and implements the AddTiles and RemoveTiles methods in PlayerScript for Issue #17 .
=> Add/Remove Tile Method Implementations

Crypto Wars/Assets/Scripts/GameManager.cs, Crypto Wars/Assets/Scripts/GameManager.cs.meta
Adds basic functionality for the GameManager script. Adds implementation of _Battle_ class which is an instance of a single battle in the game world, all battles are added to the _OngoingBattles_ List. 
I decided to add another field to the _Battle_ class that was not given in the outline, _Player winner_. I did this so that the _DoAllBattles_ function can calculate the winner of a battle, assign that winner, and continue calculating ongoing battles without exiting the function needlessly.
=> Added functionality for GameManager

Crypto Wars/Assets/Scripts/PlayerScript.cs
Resolves #35 
Fix syntax errors in relation to PlayerScript compilation errors
=> Unity Compilation Error (PlayerScript) - Fix syntax errors

Crypto Wars/Assets/Scripts/Inventory.cs, Crypto Wars/Assets/Scripts/Inventory.cs.meta, Crypto Wars/Assets/Scripts/PlayerScript.cs
Added an Inventory Class, which can
- Hold a certain number of cards
- Return if the desired card is in the inventory
- Add a card to the inventory, up until a maximum "hand size" is reached
- Remove a card from the inventory
=> Inventory Class

.github/workflows/unity_ci.yml
=> pull_request_target is said to use secrets on a fork, so testing

Crypto Wars/Assets/Scripts/EndTurn.cs, Crypto Wars/Assets/Scripts/EndTurn.cs.meta, Crypto Wars/Assets/Scripts/TurnMaster.cs, Crypto Wars/Assets/Scripts/buildingRegistry.cs.meta, Crypto Wars/Assets/Scripts/cardRegistry.cs.meta
#19 Added in a script that will be used for the End Turn Button and the Turn Counter. Since it takes from Player and turnMaster scripts, those game objects will need to be implemented in order for it to function.
=> End Turn Implementation

.github/workflows/unity_ci.yml
- This should allow altered pull requests to use the pipeline
=> Update workflow (again again again)

Crypto Wars/Assets/Scenes/EndTurnScene.unity, Crypto Wars/Assets/Scenes/EndTurnScene.unity.meta, Crypto Wars/Assets/Scripts/EndTurn.cs
#19  Added in components to the scene for the Turn Counter text output and End Turn button. The EndTurn script is placed inside the Turn Counter and the function to endPlayerTurn() is added inside the On Click () section of the End Turn button. Future work that needs to be done is adding in the PlayerController and TurnMaster scripts onto the scene. We also may need to refactor TurnMaster so that it is referencing the same players as the PlayerController.
=> Added the endTurn GUI Components to the scene

PR_Checklist.md
added the required checklist for PR review
=> added the required checklist for PR review

Crypto Wars/Assets/Scripts/Battles.cs
This PR includes a refactoring for the battle class implantation which is largely responsible for conducting the calculations needed to determine a winner off a battle. Some notable changes made include: 
- The creation of defender and attacker objects which will be included in an list of attackers and defenders in a queue which will need to be implemented in a future PR. 
- CalculateWinner() which is a function that takes a players and their cards and returns the player that wins to the GameMangerClass
- An attack function that does the actual attacking calculations between two opponents
- Swap() is a function that swaps who is the attacker and defender throughout the battle to allow both sides to attack
- IsSpecialBattle() returns a bool if a function is a special battle (will need a …
=> Added refactoring for battle class

Crypto Wars/Assets/Scenes/Project.unity, Crypto Wars/Assets/Scripts/Battles.cs
Simply fixing the errors in battles class. 
N/A
=> Fixed errors in Battles class

Crypto Wars/Assets/Scripts/Scripts.asmref, Crypto Wars/Assets/Scripts/Scripts.asmref.meta, Crypto Wars/Assets/Scripts/Test_EditMode/testPlayerScript.cs, Crypto Wars/Assets/Scripts/Test_EditMode/testPlayerScript.cs.meta
Added some test coverage for PlayerScript. This PR commit mainly tests the PlayerScript constructor.
n/a
=> Add test coverage for PlayerScript

.github/workflows/unity_ci.yml
Temporarily commented out the build section in the CI/CD pipeline test job due to unresolved issues with building scenes in the game (referenced in issue #45). This change aims to prevent pipeline failures until a permanent fix is implemented.
Temporarily Disabling Build Section: #59 and [Issue #59](https://github.com/UNLV-CS472-672/2024-S-GROUP8-CW/issues/59)
Screenshots (if appropriate):
N/A (changes are to the CI/CD configuration, no visual changes)
Closes #59
=> removed build from workflow jobs for now

Crypto Wars/Assets/Scripts/Test_EditMode/testTileScript.cs
Added NUnit tests for the Tile class to ensure that player indices, materials, and positions are set and retrieved correctly. The tests will help prevent regressions and confirm that the Tile class is functioning as intended.
=> Added testscript for tileScript

Crypto Wars/Assets/Scripts/GUI/PlayerList.cs, Crypto Wars/Assets/Scripts/PlayerController.cs, Crypto Wars/Assets/Scripts/Test_EditMode/PlayerListTest.cs
Adds functionality of PlayerList GUI element to interact with PlayerController script. This means that the PlayerList will display the correct number of players and allows information such as players color, name, and other misc. information to display during gameplay. Also adds feature to toggle visibility of GUI element by clicking directly on the PlayerList.
Solves issue [#68](https://github.com/UNLV-CS472-672/2024-S-GROUP8-CW/issues/68)
[] Bug fix (fixes a issue)
[x] New feature (new implemention of a feature)
[] Refactoring (small changes that won't impact very much)
[] Possible broken change (fix or feature that could break functionality)
[x] Have added comments and documentation
[x] I have added tests to cover my changes. 
=> Add features to PlayerList

Crypto Wars/Assets/Scripts/GameManager.cs, Crypto Wars/Assets/Scripts/Test_PlayMode/GameManagerTest.cs, Crypto Wars/Assets/Scripts/TileScript.cs
In this PR I added the CalculateWinner() function from battles into GameManager to properly loop through the battles and return the winner for each battle. After returning the winner I check to see if the winner was the attacker or the defender. If it is the attacker I remove the tile from the defender and add it to the attackers tilesOwned. I did this by adding a helper function in TileScript that loops through the players tilesOwned and gets the specific tile from the battle based on the coordinates of the tile. Additionally, I added a a function returnWinnersRemainingCardsToInventory() which after a battle will return the winners remaining cards to their inventory. Lastly, with the help of ChatGPT I added some basic unit testing to for the newly added functions in the …
=> Added rewards for winner of Battles and fixed merge issues

Crypto Wars/Assets/Scenes/GameSettings.unity, Crypto Wars/Assets/Scenes/GameSettings.unity.meta, Crypto Wars/Assets/Scripts/GUI/SettingsMenu.cs, Crypto Wars/Assets/Scripts/GUI/SettingsMenu.cs.meta, Crypto Wars/Assets/Scripts/Test_PlayMode/SettingsTest.cs, Crypto Wars/Assets/Scripts/Test_PlayMode/SettingsTest.cs.meta
This PR implements the game settings menu. Features include:
- Player Count
- Hotseat Enable/Disable
- Win Conditions
Possible issues may occur. I was working on an older branch and everything was working as intended but when I updated my branch I kept getting errors from PlayerController and cannot test it on the current version. The menu should still be working fine though. 
#125 
=> Game Settings Menu

Crypto Wars/Assets/Scripts/CreateDefenseSystem.cs, Crypto Wars/Assets/Scripts/GUI/HandManager.cs, Crypto Wars/Assets/Scripts/GUI/Stash.cs, Crypto Wars/Assets/Scripts/GameManager.cs, Crypto Wars/Assets/Scripts/PlayerController.cs, Crypto Wars/Assets/Scripts/PlayerScript.cs, Crypto Wars/Assets/Scripts/Test_EditMode/BuildingRegistryTest.cs.meta, Crypto Wars/Assets/Scripts/Test_EditMode/CardRegistryTest.cs.meta, Crypto Wars/Assets/Scripts/Test_EditMode/PlayerScriptTest.cs, Crypto Wars/Assets/Scripts/Test_PlayMode/GameManagerTest.cs, Crypto Wars/Assets/Scripts/Test_PlayMode/StashTest.cs, Crypto Wars/Assets/Scripts/TileScript.cs
Battles now work for real
Shields can be destroyed again
Fixes #130
=> Fixed battles 

.github/pull_request_template.md, PR_Checklist.md
Readded the checklist, looks it got accidentally removed at some-point.
N/A
=> Readd Checklist and fix typo in pr template
